name: 'logging'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"


on-run-start:
  - "{{ logging.create_audit_schema() }}"
  - "{{ logging.create_audit_log_table() }}"
  - "{{ logging.log_run_start_event() }}"
  
  
on-run-end:
  - "{{ logging.log_run_end_event() }}"


models:
  
  pre-hook: "{{ logging.log_model_start_event() }}" # may need to put this line in the local package
  post-hook: "{{ logging.log_model_end_event() }}" # may need to put this line in the local package
  
  logging:
    schema: meta