
name: 'event_logging_integration_tests'
version: '1.0'

profile: 'integration_tests'

require-dbt-version: ">=0.15.0"

models:
  pre-hook: "{{ logging.log_model_start_event() }}"
  post-hook: "{{ logging.log_model_end_event() }}"
